In [5]:
import numpy as np
import pandas as pd

In [6]:
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
dataset = pd.read_csv("/content/drive/MyDrive/ML-Training/Supermarket Data.csv")

In [14]:

dataset.head(2)


Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0           FDA15         9.30  ...  Supermarket Type1          3735.1380
1           DRC01         5.92  ...  Supermarket Type2           443.4228

[2 rows x 12 columns]

In [15]:
dataset.isnull().any()

Item_Identifier              False
Item_Weight                  False
Item_Fat_Content             False
Item_Visibility              False
Item_Type                    False
Item_MRP                     False
Outlet_Identifier            False
Outlet_Establishment_Year    False
Outlet_Size                  False
Outlet_Location_Type         False
Outlet_Type                  False
Item_Outlet_Sales            False
dtype: bool

In [16]:
dataset.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [17]:
dataset["Item_Weight"].fillna(dataset["Item_Weight"].mean(),inplace = True)
dataset["Outlet_Size"].fillna(dataset["Outlet_Size"].mode()[0],inplace=True)


In [18]:
dataset.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [19]:
dataset.head(10)

Item_Identifier  Item_Weight  ...        Outlet_Type  Item_Outlet_Sales
0           FDA15     9.300000  ...  Supermarket Type1          3735.1380
1           DRC01     5.920000  ...  Supermarket Type2           443.4228
2           FDN15    17.500000  ...  Supermarket Type1          2097.2700
3           FDX07    19.200000  ...      Grocery Store           732.3800
4           NCD19     8.930000  ...  Supermarket Type1           994.7052
5           FDP36    10.395000  ...  Supermarket Type2           556.6088
6           FDO10    13.650000  ...  Supermarket Type1           343.5528
7           FDP10    12.857645  ...  Supermarket Type3          4022.7636
8           FDH17    16.200000  ...  Supermarket Type1          1076.5986
9           FDU28    19.200000  ...  Supermarket Type1          4710.5350

[10 rows x 12 columns]

In [20]:
dataset["Item_Fat_Content"].unique()


array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [21]:
dataset["Item_Fat_Content"].replace(to_replace="LF",value="Low Fat",inplace=True)


In [22]:
dataset["Item_Fat_Content"].unique()

array(['Low Fat', 'Regular', 'low fat', 'reg'], dtype=object)

In [23]:
dataset["Item_Fat_Content"].replace(to_replace="low fat",value="Low Fat",inplace=True)
dataset["Item_Fat_Content"].replace(to_replace="reg",value="Regular",inplace=True)
dataset["Item_Fat_Content"].unique()


array(['Low Fat', 'Regular'], dtype=object)

In [24]:
dataset["Item_Type"].unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [25]:
dataset["Outlet_Size"].unique()

array(['Medium', 'High', 'Small'], dtype=object)

In [26]:
dataset["Outlet_Location_Type"].unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [27]:
dataset["Outlet_Type"].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [28]:
x = dataset.iloc[:,[1,2,3,4,5,8,10]].values

In [29]:
x.shape

(8523, 7)

In [30]:
x

array([[9.3, 'Low Fat', 0.016047301, ..., 249.8092, 'Medium',
        'Supermarket Type1'],
       [5.92, 'Regular', 0.019278216, ..., 48.2692, 'Medium',
        'Supermarket Type2'],
       [17.5, 'Low Fat', 0.016760075, ..., 141.618, 'Medium',
        'Supermarket Type1'],
       ...,
       [10.6, 'Low Fat', 0.035186271, ..., 85.1224, 'Small',
        'Supermarket Type1'],
       [7.21, 'Regular', 0.145220646, ..., 103.1332, 'Medium',
        'Supermarket Type2'],
       [14.8, 'Low Fat', 0.04487828, ..., 75.467, 'Small',
        'Supermarket Type1']], dtype=object)

In [31]:
y=dataset.iloc[:,11:12].values
y.shape

(8523, 1)

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [33]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,3,5,6])],remainder = "passthrough")

In [34]:
x_ct = ct.fit_transform(x)

In [35]:
x_ct.shape

(8523, 28)

In [36]:
y.shape

(8523, 1)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_ct,y,test_size=0.2,random_state = 0)
print(x_ct.shape,x_train.shape,x_test.shape)


(8523, 28) (6818, 28) (1705, 28)


In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean=False)
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)


In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
mlr = LinearRegression()
mlr.fit(x_train_sc,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
y_pred = mlr.predict(x_test_sc)

In [42]:
y_pred[1:10]

array([[2538.93224963],
       [2139.78846763],
       [2341.59203153],
       [3105.59034808],
       [3678.55352432],
       [2940.82375256],
       [2001.90408624],
       [1129.42744666],
       [1813.51434663]])

In [43]:
y_test[1:10]

array([[1201.769 ],
       [1836.2764],
       [2410.8618],
       [1549.9824],
       [3169.208 ],
       [2036.6822],
       [ 824.9262],
       [ 378.1744],
       [1573.9512]])

In [44]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_pred,y_test)
print("Accuracy:",accuracy)

Accuracy: 0.20798230709740506
