In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset=pd.read_csv('/content/drive/MyDrive/ML-Training/bank.csv')

In [4]:
dataset

age          job  marital  education  ... pdays  previous poutcome deposit
0       59       admin.  married  secondary  ...    -1         0  unknown     yes
1       56       admin.  married  secondary  ...    -1         0  unknown     yes
2       41   technician  married  secondary  ...    -1         0  unknown     yes
3       55     services  married  secondary  ...    -1         0  unknown     yes
4       54       admin.  married   tertiary  ...    -1         0  unknown     yes
...    ...          ...      ...        ...  ...   ...       ...      ...     ...
11157   33  blue-collar   single    primary  ...    -1         0  unknown      no
11158   39     services  married  secondary  ...    -1         0  unknown      no
11159   32   technician   single  secondary  ...    -1         0  unknown      no
11160   43   technician  married  secondary  ...   172         5  failure      no
11161   34   technician  married  secondary  ...    -1         0  unknown      no

[11162 rows x 17 columns]

In [5]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [6]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [8]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [9]:
x=dataset.iloc[:,4:16]
y=dataset.iloc[:,16:17]
y

deposit
0         yes
1         yes
2         yes
3         yes
4         yes
...       ...
11157      no
11158      no
11159      no
11160      no
11161      no

[11162 rows x 1 columns]

In [10]:
x

default  balance housing loan  ... campaign  pdays previous  poutcome
0          no     2343     yes   no  ...        1     -1        0   unknown
1          no       45      no   no  ...        1     -1        0   unknown
2          no     1270     yes   no  ...        1     -1        0   unknown
3          no     2476     yes   no  ...        1     -1        0   unknown
4          no      184      no   no  ...        2     -1        0   unknown
...       ...      ...     ...  ...  ...      ...    ...      ...       ...
11157      no        1     yes   no  ...        1     -1        0   unknown
11158      no      733      no   no  ...        4     -1        0   unknown
11159      no       29      no   no  ...        2     -1        0   unknown
11160      no        0      no  yes  ...        2    172        5   failure
11161      no        0      no   no  ...        1     -1        0   unknown

[11162 rows x 12 columns]

In [15]:
#convert dataframe to array
x_array=x.values

In [16]:
y_array=y.values

In [17]:
x_array

array([['no', 2343, 'yes', ..., -1, 0, 'unknown'],
       ['no', 45, 'no', ..., -1, 0, 'unknown'],
       ['no', 1270, 'yes', ..., -1, 0, 'unknown'],
       ...,
       ['no', 29, 'no', ..., -1, 0, 'unknown'],
       ['no', 0, 'no', ..., 172, 5, 'failure'],
       ['no', 0, 'no', ..., -1, 0, 'unknown']], dtype=object)

In [18]:
y_array

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [19]:
x.shape

(11162, 12)

In [20]:
y.shape

(11162, 1)

In [21]:
dataset["default"].unique()

array(['no', 'yes'], dtype=object)

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [23]:
ct=ColumnTransformer([("one",OneHotEncoder(),[0])],remainder="passthrough")
x_array_trans=ct.fit_transform(x_array)
x_array_trans

array([[1.0, 0.0, 2343, ..., -1, 0, 'unknown'],
       [1.0, 0.0, 45, ..., -1, 0, 'unknown'],
       [1.0, 0.0, 1270, ..., -1, 0, 'unknown'],
       ...,
       [1.0, 0.0, 29, ..., -1, 0, 'unknown'],
       [1.0, 0.0, 0, ..., 172, 5, 'failure'],
       [1.0, 0.0, 0, ..., -1, 0, 'unknown']], dtype=object)

In [25]:
x_array_trans.shape

(11162, 13)

In [26]:
dataset["housing"].unique()

array(['yes', 'no'], dtype=object)

In [27]:
ct=ColumnTransformer([("one",OneHotEncoder(),[0,2,3,4,6,11])],remainder="passthrough")
x_ary_trans=ct.fit_transform(x_ary)
x_ary_trans

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 1.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [1.0, 0.0, 1.0, ..., 2, -1, 0],
       [1.0, 0.0, 1.0, ..., 2, 172, 5],
       [1.0, 0.0, 1.0, ..., 1, -1, 0]], dtype=object)

In [28]:
x_ary_trans.shape

(11162, 31)

In [29]:
ct=ColumnTransformer([("one",OneHotEncoder(),[0])],remainder="passthrough")
y_ary_trans=ct.fit_transform(y_ary)
y_ary_trans

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_ary_trans,y_ary_trans,test_size=0.2,random_state=0)

In [31]:
x_train.shape

(8929, 31)

In [32]:
y_train.shape

(8929, 2)

In [33]:
x_test.shape

(2233, 31)

In [34]:
y_test.shape

(2233, 2)